version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: job_offer_db_2
      POSTGRES_USER: actual_username
      POSTGRES_PASSWORD: actual_password
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U actual_username"]
      interval: 10s
      timeout: 5s
      retries: 5

  job-offer-management:
    build: ./offer-service
    container_name: job-offer-management
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/job_offer_db_2
      SPRING_DATASOURCE_USERNAME: actual_username
      SPRING_DATASOURCE_PASSWORD: actual_password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8040:8080"

  postgresdb:
    image: postgres:latest
    container_name: candidate_ms
    environment:
      - POSTGRES_PASSWORD=ilyas
      - POSTGRES_USER=postgres
      - POSTGRES_DB=candidateDB
    ports:
      - '5432:5432'

  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    depends_on:
      - postgresdb

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "9999:9999"
    expose:
      - '9999'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-server:8761/eureka/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      discovery-server:
        condition: service_healthy

  candidate-service:
    build: ./candidate-service
    container_name: candidate-service
    ports:
      - "8070:8070"
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-server:8761/eureka/
      - CONFIG_SERVICE_URL=http://config-server:9999
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8070/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      config-server:
        condition: service_healthy

  web:
    image: anassbe/flask_app-web
    ports:
      - "5000:5000"
    environment:
      - GENAI_API_KEY=${GENAI_API_KEY}
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=anass
      - DB_NAME=job_matching
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: anass
      MYSQL_DATABASE: job_matching
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  keycloak:
    container_name: keycloak-ms
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - "start-dev"
    depends_on:
      candidate-service:
        condition: service_healthy

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8222:8222"
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-server:8761/eureka/
      - CONFIG_SERVICE_URL=http://config-server:9999
    depends_on:
      - keycloak

volumes:
  postgres-data:
  db-data: