version: '3.8'
services:
  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    expose:
      - '8761'
    networks:
      - smart-interview-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      retries: 4

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "9999:9999"
    expose:
      - '9999'
    networks:
      - smart-interview-network
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-server:8761/eureka/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      discovery-server:
        condition: service_healthy

  candidate-service:
    build: ./candidate-service
    container_name: candidate-service
    ports:
      - "8070:8070"
    networks:
      - smart-interview-network
    environment:
      - CONFIG_SERVICE_URL=http://config-server:9999
    depends_on:
      config-server:
        condition: service_healthy

networks:
  smart-interview-network:
    driver: bridge
