version: '3.8'
services:
  config-server:
    image: ilyaselmabrouki/config-server
    container_name: config-server
    ports:
      - "9999:9999"
    networks:
      - my-network
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-server:8761/eureka/
    depends_on:
      - discovery-server

  discovery-server:
    image: ilyaselmabrouki/discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
