version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: job_offer_db
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    image: sosouca/joboffers-server  # Use the Docker Hub image
    container_name: job_offer_app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/job_offer_db
      SPRING_DATASOURCE_USERNAME: your_username
      SPRING_DATASOURCE_PASSWORD: your_password

  postgresdb:
    image: postgres:latest
    container_name: candidate_ms
    environment:
      - POSTGRES_PASSWORD=ilyas
      - POSTGRES_USER=postgres
      - POSTGRES_DB=candidateDB
    ports:
      - '5432:5432'

  discovery-server:
    image: ilyaselmabrouki/discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    depends_on:
      - postgresdb

  config-server:
    image: ilyaselmabrouki/config-server
    container_name: config-server
    ports:
      - "9999:9999"
    expose:
      - '9999'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-server:8761/eureka/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    depends_on:
      discovery-server:
        condition: service_healthy

  candidate-service:
    image: ilyaselmabrouki/candidate-service
    container_name: candidate-service
    ports:
      - "8070:8070"
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-server:8761/eureka/
      - CONFIG_SERVICE_URL=http://config-server:9999
    depends_on:
      config-server:
        condition: service_healthy

volumes:
  postgres-data: