name: CI/CD Pipeline for Dockerization

on:
  push:
    branches:
      - main

jobs:
  build-and-push-config-server:
    name: Build Config Server Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution : 'corretto'
          java-version: '17'

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml
        working-directory: ./config-server

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: ./config-server
          dockerfile: Dockerfile
          push: false
          tags: ilyaselmabrouki/config-server:latest

  build-and-push-discovery-service:
    name: Build Discovery Service Docker Image
    runs-on: ubuntu-latest
    needs: build-and-push-config-server

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml
        working-directory: ./discovery-server

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: ./discovery-server
          dockerfile: Dockerfile
          push: false
          tags: ilyaselmabrouki/discovery-server:latest
